version: '3.4'

services:
  editor:
    restart: always
    image: node:16-alpine
    working_dir: /var/www/html
    expose:
      - 3000
    command:
      - "yarn install --network-timeout=15000"
      - "yarn dev"
    hostname: editor
    entrypoint: 'sh -c "yarn install --ignore-platform; yarn run ${DEV_COMMAND:-dev}"'
    environment:
      TZ: "Europe/Prague"
      NODE_OPTIONS: "--max-old-space-size=2048 --inspect"
      DEV_COMMAND: "dev"
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - "3000:3000"
    networks:
      proxy:

volumes:
  node_modules:

networks:
  proxy:
    external: true
